/**
 * Barrel de mockups da plataforma (UI ilustrativa do Omni Headers).
 */
export { AppWindow } from './AppWindow'
export { InboxMockup } from './InboxMockup'
export { HeroShowcase } from './HeroShowcase'
export { ChannelOrbit } from './ChannelOrbit'
export { BotFlow } from './BotFlow'
export { DashboardMockup } from './DashboardMockup'
export { DashboardScene } from './DashboardScene'
export { IntegrationsConstellation } from './IntegrationsConstellation'
export { MobileFrame } from './MobileFrame'
export { ChaosScene } from './ChaosScene'
export { RealidadeHojeScene } from './RealidadeHojeScene'
export { HeroOperacaoScene } from './HeroOperacaoScene'
export { AtendimentoColaborativoScene } from './AtendimentoColaborativoScene'
export { WhatsAppOficialScene } from './WhatsAppOficialScene'
export { AIComposer } from './AIComposer'
export { CaptainIAScene } from './CaptainIAScene'
export { GestaoEquipeScene } from './GestaoEquipeScene'
export { ParceiraScene } from './ParceiraScene'
export { IntegracoesScene } from './IntegracoesScene'
export { CrescimentoScene } from './CrescimentoScene'
export { TransformacaoScene } from './TransformacaoScene'
export { CTAFinalScene } from './CTAFinalScene'
export { BarChart, LineChart, DonutChart, Gauge, Sparkline } from './charts'
