/**
 * Barrel da camada de SECOES (blocos da Home, na ordem do storytelling).
 */
export { HeroSection } from './HeroSection'
export { TrustBar } from './TrustBar'
export { OperacaoHojeSection } from './OperacaoHojeSection'
export { AtendimentoSection } from './AtendimentoSection'
export { WhatsAppSection } from './WhatsAppSection'
export { IASection } from './IASection'
export { GestaoSection } from './GestaoSection'
export { ParceiraSection } from './ParceiraSection'
export { IntegracoesSection } from './IntegracoesSection'
export { CrescimentoSection } from './CrescimentoSection'
export { TransformacaoSection } from './TransformacaoSection'
export { RespostaRapidaSection } from './RespostaRapidaSection'
export { ChannelsSection } from './ChannelsSection'
export { FeaturesSection } from './FeaturesSection'
export { AutomationSection } from './AutomationSection'
export { DashboardSection } from './DashboardSection'
export { ResultsSection } from './ResultsSection'
export { HeadersSolutionSection } from './HeadersSolutionSection'
export { SegmentsSection } from './SegmentsSection'
export { TestimonialsSection } from './TestimonialsSection'
export { FAQSection } from './FAQSection'
export { FinalCTASection } from './FinalCTASection'
